### ISSUE TITLE
File not found: /app/styles/app.scss

### ISSUE THREAD

**Issue by jamesstaub** [onehilltech/ember-cli-mdc#4]
I get the following error when booting my app after installing any ember-cli-mdc module. 

```
Build Error (SassCompiler)

File not found: /app/styles/app.scss
in any of the following include paths:
  /var/folders/j3/ch6_9v7s41j8n13m96s7smfc0000gp/T/broccoli-328852ZG8VR9MaAox/out-528-broccoli_merge_trees
  node_modules
  app/styles
```

I am running ember 3.7.1
I am using ember-cli-sass, I have a ` /app/styles/app.scss`  file and the following in my ember-cli-build.js

``` 
sassOptions: {
  extension: 'scss',
   includePaths: ['node_modules']
},
```

Any recommendations?

**Comment by jamesstaub** [comment]
**update**: removing ember-cli-sass seems to have fixed the problem

**Comment by hilljh82** [comment]
@jamesstaub First, thank you for your interest in using the project. If you are using it for any public product, it would be good to know so we can track how `ember-cli-mdc` is being used. Second, I was going to suggest removing `ember-cli-sass` from your project. `ember-cli-mdc` has its own integration of the sass compiler because `ember-cli-sass` does not work well with `material-components-web`. When using `ember-cli-sass`, it take about 30 second to 2 minutes for your project to recompile for each change if you have live updates enabled. We worked really hard to resolve this problem so you get the same experience you are used to when using `ember-cli-mdc`.

With all that being said, I will update the `README.md` with this notice/warning, and update the build engine to print an error message and stop if you have `ember-cli-sass` installed.

**Comment by jamesstaub** [comment]
Thanks for the info, and for your work on this package! My company is trying this package for a customer-facing product but it is not yet public. We were drawn to this package over ember paper because paper does not implement the most recent version of material design components.

**Comment by Shajansheriff** [comment]
I am facing the same slow re-compile issue in my app when i directly tried to use `material-components-web` with `ember-cli-sass`.  @hilljh82  Could be please shed some light on why it is taking more than 30sec-1min to recompile? How do you solve the issue by building `ember-cli-mdc-sass` ? It would be really helpful to understand the scenario.
